CREATE DATABASE VENTAS;
USE VENTAS;

CREATE TABLE PRODUCTO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO CHAR(8) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    MARCA VARCHAR(40) NOT NULL,
    MODELO VARCHAR(40) NOT NULL,
    PRECIO DOUBLE NOT NULL,
    CANTIDAD INT NOT NULL
);

CREATE TABLE CLIENTES(
    ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(40) NOT NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    RUC CHAR(11) NOT NULL
);

CREATE TABLE PROVEEDORES(
    ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(40) NOT NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    TELEFONO CHAR(9) NOT NULL
);

SELECT * FROM PRODUCTO;
SELECT * FROM CLIENTES;
SELECT * FROM PROVEEDORES;



-- DELETE FROM PRODUCTO WHERE ID = 55;

-- INSERT INTO PRODUCTO (codigo, nombre, marca, modelo, precio, cantidad)
-- VALUES ("C2", "A", "A", "A", 1, 1);

-- Eliminar base de datos existente:
-- DROP DATABASE VENTAS;

-- Eliminar tabla de BD:
-- DROP TABLE CLIENTES;