package libreria.vista;

import libreria.controlador.PrestamoController;

public class frmGestionPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form frmGestionPrestamos
     */
    public frmGestionPrestamos() {
        setResizable(false);
        setTitle("Gestión de Préstamos");
        setLayout(null);
        setSize(400, 350);

        javax.swing.JLabel lblDni = new javax.swing.JLabel("DNI Cliente:");
        javax.swing.JLabel lblIsbn = new javax.swing.JLabel("ISBN Libro:");
        javax.swing.JLabel lblDias = new javax.swing.JLabel("Días de Préstamo:");
        
        txtDniCliente = new javax.swing.JTextField();
        txtIsbnLibro = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton("Registrar Préstamo");
        btnVolver = new javax.swing.JButton("Volver");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipal m = new MenuPrincipal();
                m.setVisible(true);
                dispose();
            }
        });

        lblDni.setBounds(50, 40, 100, 25);
        txtDniCliente.setBounds(180, 40, 150, 25);
        
        lblIsbn.setBounds(50, 80, 100, 25);
        txtIsbnLibro.setBounds(180, 80, 150, 25);
        
        lblDias.setBounds(50, 120, 120, 25);
        txtDias.setBounds(180, 120, 150, 25);
        
        btnRegistrar.setBounds(50, 190, 150, 30);
        btnVolver.setBounds(220, 190, 110, 30);

        add(lblDni);
        add(txtDniCliente);
        add(lblIsbn);
        add(txtIsbnLibro);
        add(lblDias);
        add(txtDias);
        add(btnRegistrar);
        add(btnVolver);
        
    }
    public void setController(libreria.controlador.PrestamoController controller) {
        this.controller = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGestionPrestamos().setVisible(true);
            }
        });
    }
    
public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnVolver;
    public javax.swing.JTextField txtDias;
    public javax.swing.JTextField txtDniCliente;
    public javax.swing.JTextField txtIsbnLibro;
    private libreria.controlador.PrestamoController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
